### ISSUE TITLE
how to conceal private key in the python code?

### ISSUE THREAD

**Issue by chenmingzhang** [matze/python-phant#24]
i always need to write my private key explicitly in the python code:
p = Phant(publicKey='xyzpublickey', fields=['temp', 'humid'], privateKey='abcprivatekey')

is there any way i can conceal my private key as i did in wpa_supplicant?
password=hash:7c2d7f0711f29d05c5dfd95e9df04e0c

thanks

**Comment by matze** [comment]
Your issue is independent of this module …

You could read the password from a (encrypted) file, you could use your system's keyring manager, you could read the password from stdin via [getpass](https://docs.python.org/2/library/getpass.html) but that's not a decision I will take for you or impose on everyone.
